# Generated by Django 5.1.7 on 2025-05-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
